### ISSUE TITLE
Home page link "beta 2" goes to "beta 1"

### ISSUE THREAD

**Issue by bkidwell** [indiebox/ubos-docs#15]
This link goes to http://ubos.net/blog/2014/11/24/ubos-beta1-available/

![temp](https://cloud.githubusercontent.com/assets/723919/6143151/50f1812c-b191-11e4-8a33-53a7840cd93c.png)

**Comment by indiebox** [comment]
Fixed by c8d0c92973dc7da11de739678759dbfccd4f8015
